### ISSUE TITLE
Order creation: response when new payment method is selected

### ISSUE THREAD

**Issue by jsperezg** [podemos-info/census#93]
When a new payment method is selected the API should return the payment method id otherwise it will be impossible to manage recurrent payments based on this first creation.

**Comment by jsperezg** [comment]
same with this parameter:

return_url : After payment back URL (string must include __RESULT__ that will be replaced by ok or ko)

It should allow another parameter to return back the new payment method id

**Comment by leio10** [comment]
Ok, the first case is easy, it would return a `payment_method_id` in the resulting JSON when the order is created.
The second case is pretty complicated, as the order and the payment method is not persisted until the payment gateway result is received. Also, you should not trust in the `return_url` to be called to confirm the payment result. I suppose we will need an additional callback to solve this :disappointed: :disappointed:
To avoid further complications, I'd try to use the same solution for every case, regardless of the chosen payment method.

**Comment by leio10** [comment]
Finally, I'm saving the order and the payment method before the credit card authorization. You can check the code changes at 3ea2e5c and API changes at https://github.com/podemos-info/census/blob/enhancement/api-payments/API.md
Tests are not passing yet, since Redsys communications have changed and I've to update server requests and responses. So, it still will take some time to merge this branch.

**Comment by leio10** [comment]
Implemented at #99.
